### PR TITLE
Stylesheet

### PR DESCRIPTION
**Pull request by daudi13**
#In this project I:

-Added a .html file with the text "Hello Microverse"
-Added a .css file that changes the text to a color of my liking
-Added a .gitignore 
-Added each file on a unique commit
-Added a README.md file with a description of the project
-Used Github flow
-Created a new branch
-Created a test.md file and added it to .gitignore, along with the node_modules folder
-Set up linters

### CODE REVIEW

**Comment by daudi13** [comment]
How do I clear the errors on Linters / Lighthouse and Linters / Webhint

**Review by FrederickMih — CHANGES_REQUESTED** [review]
Hi @daudi13 , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️

- [ ] Please, do not open a new Pull Request for re-reviews.
- [ ] Some linters are still failing. Please let's fix it.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by daudi13** [comment]
how do I solve the two linter problems that have not passed the checks

**Comment by daudi13** [comment]
Please let me know how I make changes to the existing pull request without creating another pull request.

**Pull request closed without merging**
